In [1]:
import pandas as pd
import numpy as np
pd.__version__

'3.0.6'

In [19]:
# Q2. Records count
dataset = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
print(len(dataset))
dataset.head()

10000

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [3]:
# Q3. Fuel types
set(dataset['fuel_type'])

{'Diesel', 'Gasoline', 'Hybrid'}

In [4]:
# Q4. Missing values
dataset.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [5]:
# Q5. Max fuel efficiency
asia_rows = dataset[dataset["origin"] == "Asia"]
asia_rows.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [6]:
asia_rows["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [7]:
dataset["horsepower"].median()

np.float64(254.0)

In [8]:
dataset["horsepower"].mode()[0]

np.float64(252.0)

In [9]:
# Q6. Median value of horsepower
# Median horsepower 
median = dataset["horsepower"].median()
median

np.float64(254.0)

In [10]:
# Most frequent horsepower i.e mode
most_frequent = dataset["horsepower"].mode()[0]
most_frequent

np.float64(252.0)

In [11]:
# Fillna
dataset["horsepower"] = dataset["horsepower"].fillna(most_frequent)

In [12]:
# Median new
median_new = dataset["horsepower"].median()
median_new

np.float64(252.0)

In [14]:
# Q7. Sum of weights
X = dataset[dataset["origin"] == "Asia"][["vehicle_weight", "model_year"]].head(7).values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = np.linalg.inv(X.T @ X) @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [15]:
w.sum()

np.float64(0.36919696904925486)